version: '3.1'
services:
  server:
    build: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/emw-stat
      - POSTGRES_USER=emwuser
      - POSTGRES_PASSWORD=emwuser

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=emw-stat
      - POSTGRES_USER=emwuser
      - POSTGRES_PASSWORD=emwuser

  main-service:
    build: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - main-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://emw-db:5432/emw-main
      - POSTGRES_USER=emwuser
      - POSTGRES_PASSWORD=emwuser
      - stat-server.url=http://main-service:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: emw-db
    ports:
      - "6547:5432"
    environment:
      - POSTGRES_DB=emw-main
      - POSTGRES_USER=emwuser
      - POSTGRES_PASSWORD=emwuser
